version: "3.9"
services:
  app:
    build: ./docker
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mimic4
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    command: python -m pipeline.extract

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mimic4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - C:/Users/fluff/Documents/mimic-code:/mimic-code
      - C:/Users/fluff/Documents/Github/mimic-pipeline/data/raw:/mimic-data
    ports:
      - "5432:5432"

volumes:
  pgdata: